base:
  project: banking_prediction
  test_size: 0.2
  random_state: 42

data_source:
  local_data_source: data/dataset_raw/banking.csv
  preprocessed_data_source: data/dataset_processed/banking_processed.csv

pipeline:
  preprocessor_path: model_dir/Preprocessor/Preprocessor.joblib

classifier:
  RandomForestClassifier:
    params:
      
metrics_path:
  roc_auc_plot_path: src/roc_auc_curve.png
  confusion_matrix_path: src/confusion_matrix.png


model_dir: model_dir/tuned_model/model_final.pkl


ml_flow_config:
  remote_server_uri: http://localhost:5001

  experiment_name: Experiment 
  run_name: ML Run 

  registered_model_name: Banking_Classifier

  production_model_path: prediction_service/production_model.pkl


  


